seed_everything: 20220118
experiment_subdir_base: logs/mnist_bin/compare/model_size/refit_encoder_testcomp/x025/q50/iwae_dr03_i5_stl
# add_checkpoint_callback: True
data:
  setup_seed: 20220118
  dataset: mnist_bin
  use_test_instead_val: False
  use_test_instead_train: True
  batch_size: 200
  test_batch_size: 5
  missingness: 'uniform'
  total_miss_train: 0.00
  total_miss_val: 0.00
  total_miss_test: 0.00
  pre_imputation: 'oracle'
  pre_impute_val: false
  filter_fully_missing_train: true
  filter_fully_missing_val: true
  filter_fully_missing_test: true
  data_root: ./data
refit_model:
  refit_encoder_class: standard
  var_latent_STL: True
  var_latent_DREG: False
  num_latent_samples: 1
  num_importance_samples: 5

  num_test_importance_samples: 1000

  lr_latent: 1e-4
  amsgrad_latent: True
  use_lr_scheduler: True
model_class: IWAE_FID
model_path: ./logs/mnist_bin/compare/model_size/x025/q50/iwae_dr03_i5_stl/seed_{}/lightning_logs/version_{}/checkpoints/last.ckpt
load_best_model: True
trainer:
  # logger: true
  # checkpoint_callback: null
  # enable_checkpointing: true
  # callbacks: null
  # default_root_dir: null
  gradient_clip_val: 5
  gradient_clip_algorithm: norm
  # process_position: 0
  # num_nodes: 1
  # num_processes: 1
  # devices: null
  # gpus: null
  # auto_select_gpus: false
  # tpu_cores: null
  # ipus: null
  # log_gpu_memory: null
  # progress_bar_refresh_rate: null
  # enable_progress_bar: true
  # overfit_batches: 0.0
  # track_grad_norm: -1
  # check_val_every_n_epoch: 1
  # fast_dev_run: false
  # accumulate_grad_batches: null
  max_epochs: 200
  # min_epochs: null
  # max_steps: -1
  # min_steps: null
  # max_time: null
  # limit_train_batches: 1.0
  # limit_val_batches: 1.0
  # limit_test_batches: 1.0
  # limit_predict_batches: 1.0
  # val_check_interval: 1.0
  # flush_logs_every_n_steps: null
  log_every_n_steps: 1
  # accelerator: null
  # strategy: null
  # sync_batchnorm: false
  # precision: 32
  # enable_model_summary: true
  # weights_summary: top
  # weights_save_path: null
  # num_sanity_val_steps: 2
  # resume_from_checkpoint: null
  # profiler: null
  # benchmark: false
  # deterministic: false
  # reload_dataloaders_every_n_epochs: 0
  # reload_dataloaders_every_epoch: false
  # auto_lr_find: false
  # replace_sampler_ddp: true
  # detect_anomaly: false
  # auto_scale_batch_size: false
  # prepare_data_per_node: null
  # plugins: null
  # amp_backend: native
  # amp_level: null
  # move_metrics_to_cpu: false
  # multiple_trainloader_mode: max_size_cycle
  # stochastic_weight_avg: false
  # terminate_on_nan: null
