seed_everything: 20220118
experiment_subdir_base: logs/uci_hepmass/compare/vae_z5_stl_complete
add_checkpoint_callback: True
data:
  setup_seed: 20220118
  dataset: uci_hepmass
  use_test_instead_val: False
  batch_size: 512
  missingness: 'uniform'
  total_miss_train: 0.0
  total_miss_val: 0.0
  pre_imputation: 'oracle'
  pre_impute_val: false
  filter_fully_missing_train: true
  filter_fully_missing_val: true
  data_root: ./data
model:
  class_path: vgiwae.models.VAE
  init_args:
    generator_network:
      class_path: vgiwae.shared.neural_nets.ResidualFCNetwork
      init_args:
        input_dim: 16
        output_dim: 42
        num_residual_blocks: 2
        residual_block_dim: 256
        dropout_probability: 0.0
        activation: relu
    generator_distribution: normal_with_eps
    prior_distribution: std_normal
    var_latent_network:
      class_path: vgiwae.shared.neural_nets.ResidualFCNetwork
      init_args:
        input_dim: 21
        output_dim: 32
        num_residual_blocks: 2
        residual_block_dim: 256
        dropout_probability: 0.0
        activation: relu
    var_latent_distribution: normal_with_eps
    encoder_use_mis_mask: False
    kl_analytic: False
    var_latent_STL: True
    num_latent_samples: 5
    lr_generator: 1e-3
    lr_latent: 1e-3
    amsgrad_generator: True
    amsgrad_latent: True
    use_lr_scheduler: True
    init_imputation_distribution: false
    num_imputations_train: 1
    num_imputations_val: 1
    imputation_init_train: empirical
    imputation_init_val: empirical
trainer:
  # logger: true
  # checkpoint_callback: null
  # enable_checkpointing: true
  # callbacks: null
  # default_root_dir: null
  gradient_clip_val: 5
  gradient_clip_algorithm: norm
  # process_position: 0
  # num_nodes: 1
  # num_processes: 1
  # devices: null
  # gpus: null
  # auto_select_gpus: false
  # tpu_cores: null
  # ipus: null
  # log_gpu_memory: null
  # progress_bar_refresh_rate: null
  # enable_progress_bar: true
  # overfit_batches: 0.0
  # track_grad_norm: -1
  # check_val_every_n_epoch: 1
  # fast_dev_run: false
  # accumulate_grad_batches: null
  # max_epochs: 1000
  # min_epochs: null
  max_steps: 200000
  # min_steps: null
  # max_time: null
  # limit_train_batches: 1.0
  # limit_val_batches: 1.0
  # limit_test_batches: 1.0
  # limit_predict_batches: 1.0
  # val_check_interval: 1.0
  # flush_logs_every_n_steps: null
  log_every_n_steps: 1
  # accelerator: null
  # strategy: null
  # sync_batchnorm: false
  # precision: 32
  # enable_model_summary: true
  # weights_summary: top
  # weights_save_path: null
  # num_sanity_val_steps: 2
  # resume_from_checkpoint: null
  # profiler: null
  # benchmark: false
  # deterministic: false
  # reload_dataloaders_every_n_epochs: 0
  # reload_dataloaders_every_epoch: false
  # auto_lr_find: false
  # replace_sampler_ddp: true
  # detect_anomaly: false
  # auto_scale_batch_size: false
  # prepare_data_per_node: null
  # plugins: null
  # amp_backend: native
  # amp_level: null
  # move_metrics_to_cpu: false
  # multiple_trainloader_mode: max_size_cycle
  # stochastic_weight_avg: false
  # terminate_on_nan: null
